---

- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
  args:
    creates: $HOME/.nvm/nvm.sh

- name: Install Node
  shell: |
    # Load nvm fist after installation
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

    nvm install {{ node_version }} --lts --latest-npm
    nvm alias default {{ node_version }}
  args:
    creates: "$HOME/.nvm/versions/node/v{{ node_version }}*"

- name: Remove nvm configuration to .bashrc
  lineinfile:
    path: $HOME/.bashrc
    state: absent
    regexp: ".*NVM.*"

- name: Add extra nvm configuration to .extra
  blockinfile:
    path: $HOME/.extra
    marker: "# {mark} ANSIBLE MANAGED NVM BLOCK"
    create: yes
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
