---

- name: Dock - Set dock tilesize.
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: 33
  notify: Restart Dock

- name: Dock - Automatically hide dock.
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  notify: Restart Dock

- name: Dock - Move it to the left.
  osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: left
  notify: Restart Dock

- name: Dock - Show indicator lights for open applications in the dock.
  osx_defaults:
    domain: com.apple.dock
    key: show-process-indicators
    type: bool
    value: true
  notify: Restart Dock

- name: Dock - Make dock icons of hidden applications translucent.
  osx_defaults:
    domain: com.apple.dock
    key: showhidden
    type: bool
    value: true
  notify: Restart Dock

- name: Dock - Show only active apps.
  osx_defaults:
    domain: com.apple.dock
    key: static-only
    value: true
  notify: Restart Dock


- name: Hot corners - Bottom right corner puts screen to sleep
  osx_defaults:
    domain: com.apple.dock
    key: '{{ item.key }}'
    value: '{{ item.value }}'
    type: int
  with_items:
    - {'key': 'wvous-br-corner', 'value': 10}
    - {'key': 'wvous-br-modifier', 'value': 0}
  notify: Restart Dock
