---

- name: Finder - Keep folders on top when sorting by name.
  osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true
  notify: Restart Finder

- name: Finder - Show pathbar in bottom of finder.
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
  notify: Restart Finder

- name: Finder - Show statusbar.
  osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
  notify: Restart Finder

- name: Finder - allow quitting via ⌘ + Q
  osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    type: bool
    value: true
  notify: Restart Finder

- name: Finder - custom default location for new Finder windows
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: PfLo
  notify: Restart Finder

- name: Finder - new window opens in home folder
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: "file://${HOME}"
  notify: Restart Finder


- name: Finder - add link to iCloud Drive inside home
  file:
    src: $HOME/Library/Mobile Documents/com~apple~CloudDocs
    dest: $HOME/iCLoud Drive
    state: link

# Uses beorg application path
- name: Finder - add link to org folder inside home
  file:
    src: $HOME/Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org
    dest: $HOME/org
    state: link
