---

- name: Require password after sleep or screen saver begins
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    value: 1
    type: int

- name: Require password 5 seconds after sleep of screen saver begins
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    value: 5
    type: int

- import_tasks: dock.yml

- import_tasks: finder.yml

- import_tasks: ui.yml

- import_tasks: trackpad.yml
