---

- name: Trackpad - enable tap to click
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    value: true
    type: bool
  notify: Restart Prefs

- name: Keyboard - Enable full keyboard access for all controls
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    value: 3
    type: int

- name: Keyboard - Disable press-and-hold for keys in favor of key repeat
  osx_defaults:
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    value: false
    type: bool
