---
- name: Cask - Add tap for versions
  homebrew_tap:
    name: "{{ item }}"
  with_items:
    - homebrew/cask-drivers
    - homebrew/cask-versions

- name: Cask - Install Cask applications
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    # - adobe-photoshop-lightroom600
    # - agenda
    # - bartender
    # - copyclip
    # - microsoft-office
    # - rambox
    # - spectacle
    - 1password
    - alfred
    - appcleaner
    - bettertouchtool
    - captin
    - chromedriver
    - docker
    - dozer
    - dropbox
    - firefox
    - gitter
    - google-chrome
    - gpg-suite
    - grammarly
    - iina
    - kap
    - karabiner-elements
    - keybase
    - keycastr
    - luna-display
    - maccy
    - mattermost
    - menumeters
    - minikube
    - podcastmenu
    - postman
    - rectangle
    - skype
    - slack
    - spotify
    - virtualbox
    - visual-studio-code
    - whatsapp
    - zoom
