---
- name: Install homebrew basic formulae
  homebrew:
    name: [
    # Install GNU core utilities (those that come with macos ... suck).
    # Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
    'coreutils',
    # Install some other useful utilities like `sponge`.
    'moreutils',
    # Install GNU `find`, `locate`, `updatedb`, and `xargs`
    'findutils',
    # Install GNU sed, overwriting the built-in sed.
    'gnu-sed',
    # Install latest bash
    'bash',
    'bash-completion',
    # Install GnuPG to enable PGP-signing commits.
    'gnupg',
    # Install other useful binaries.
    'openssh',
    'tmux',
    'git',
    'git-extras',
    'ghi',
    'hub',
    'ispell',
    'ag',
    'ack',
    'colordiff',
    'tree',
    'wget',
    # Show system information on the terminal
    'neofetch',
    # Better man pages for lazy people
    'tldr',
    # Top for humans
    'htop',
    # Command-line fuzzy finder.
    'fzf',
    # Cat clone with wings.
    'bat',
    # JSON processor.
    'jq',
    # HTTP client.
    'httpie',
    # Swiss Army Knife for macOS.
    'm-cli',
    # Get the password of the WiFi you're on.
    'wifi-password',
    # A simple, fast and user-friendly alternative to 'find'
    'fd',
    # Manage several Java environments
    'jenv',
    # PostgreSQL client
    'libpq',
    ]


- name: Add psql client to the path
  blockinfile:
    path: $HOME/.extra
    create: yes
    block: |
      # psql is a keg-only formula
      export PATH="/usr/local/opt/libpq/bin:$PATH"
