---
- name: Install iTerm2 through Homebrew
  homebrew_cask:
    name: iterm2
    install_options: 'appdir=/Applications'
    state: present

- name: Install iTerm2 settings
  file:
    src: '{{ role_path }}/files/com.googlecode.iterm2.plist'
    dest: '$HOME/Library/Preferences/com.googlecode.iterm2.plist'
    state: link
    force: yes
